services:
  product-service:
    container_name: product-service
    image: mrtrlle/product-service

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jfs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8080:8080"
    networks:
      - link
  db:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: jfs
    ports:
      - "5332:5432"
    networks:
      - link
    restart: unless-stopped
    volumes:
      - db:/data/postgres
networks:
  link:
    driver: bridge
volumes:
  db: