name: Build workflow
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jfs
        options: >-
          --health-cmd="pg_isready -U postgres -d jfs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Make mvnw executable (if you use wrapper)
        run: chmod +x mvnw || true
      - name: Maven Clean Verify
        run: ./mvnw -B -ntp clean verify || mvn -B -ntp clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jfs
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
