name: Build workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0000
          POSTGRES_DB: jfs
        # healthcheck so the job waits until Postgres is ready
        options: >-
          --health-cmd="pg_isready -U postgres -d jfs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven Clean Verify
        run: ./mvnw -B -ntp clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jfs
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 0000
          # uncomment the next line once if Flyway complains about existing schema without history table
          # SPRING_FLYWAY_BASELINE_ON_MIGRATE: 'true'
